#!/usr/bin/env python3

from pathlib import Path

public = Path('public/').mkdir(exist_ok=True)

from openings import bg
bg.save_svg('openings.svg')

#   with open('public/index.html', 'w') as index:
#       index.write('<!doctype html><html><title>Openings</title><object data="openings.svg" type="image/svg+xml">')
