#!/usr/bin/env python3

from pathlib import Path
from sh import mkdir, mv, rm, touch, bash, ls


ls('-la')
mkdir('-p', 'public/png_cache')

from openings import bg
bg.save_svg('openings.svg')
#   touch('openings.svg')
#   mkdir('png_cache')

mv('-f', 'openings.svg', 'public')

bash('-c', '(tar c png_cache) | (tar xf - -C public)')

with open('public/index.html', 'w') as index:
    index.write('<!doctype html><html><title>Openings</title><object data="openings.svg" type="image/svg+xml">')
