name: Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Generate Pages
      run: |
        sudo apt update
        sudo apt install graphviz
        git clone https://github.com/ph1t0/estatico.git
        ls
        pwd
        pip install -r requirements.txt
        ./build 
        sed -i "/FREEZE_FOLDER = /c\FREEZE_FOLDER = $(pwd)/public" estatico/estatico/config.cfg
        cat estatico/estatico/config.cfg
        cd estatico
        make pages
        cp openings.svg public/
        cp -r .png_cache public/
        echo '<img src="openings.svg">' >> public/index.html
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
